version: '3.9'
services:
  web:
    build: .
    ports:
      - '80:8080'
    environment:
      - VITE_API_URL=http://localhost:8080


# client:
#     build:
#       context: ./email-client
#       args:
#         - VITE_API_URL=${VITE_API_URL}
#     depends_on:
#       - server
#     ports:
#       - '80:8080'